blog/urls.py
from blog.views import PostListView
from django.urls import path
from . import views

app_name = 'blog'
# this is application namespace, this allows us to organize URLs by application and use the name when referring to them

urlpatterns = [
    # post views
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    # The above int and slug parameters are called as path converters
    # The name parameter allows us to name the URL project-wide.

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

# Making a custom manager sets to interact with the DB
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    # STATUS_CHOICES is the list, that is handed over to choices option of the field
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    # slug is a short form for something containing only letters, numbers or hypens
    # A SlugField is used to store and generate URLs for dynamically generated web pages
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    # User model is the defaut model for authentication in Django
    # CASCADE will delete the all the posts of a user if the related User is deleted
    # related_post attribute helps to access the related objects easily
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    # auto_now and auto_now_add are creation and modification T/S
    # auto_now_add is used for tracking when a new row in the DB was created as it saves the T/S when the row, was added to the DB
    # auto_now is used for tracking, when the row in the DB was last modified
    updated = models.DateTimeField(auto_now = True)
    # auto_now gives the current date time value
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    # choices parameter helps to set the status field only to one of the given parameter


    class Meta:
        ordering = ('-publish',)
        # sorts the list of posts in the descending order when, we query the DB
        # Descinding order is specified, using the negative prefix

    def __str__(self):
        # Used to get the string representation of an object
        return self.title

    objects = models.Manager() # The default manager
    published = PublishedManager() # Our custom manager

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    # related_name attribute, specifies the name from the Post to the commments like "A post has many commnets".
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django import http
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail

# Create your views here.

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 1
    template_name = 'blog/post/list.html'

# def post_list(request):
#     # The request parameter is parameter required by all the views
#     # posts = Post.published.all()
#     object_list = Post.published.all()
#     paginator = Paginator(object_list, 1) # 3 posts in a single page
#     page = request.GET.get('page')
#     # the above parameter, indicates the current page number
#     try:
#         posts = paginator.page(page)
#     except PageNotAnInteger:
#         # If page is not an integer, deliver the first page
#         posts = paginator.page(1)
#     except EmptyPage:
#         # If page is out of range deliver last page of results
#         posts = paginator.page(paginator.num_pages)
#     return render(request, 'blog/post/list.html', {'page':page, 'posts': posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    # get_object_or_404, retives the desired object from the Post model and returns a HTTP 404 error, if no such object is found

    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create a comment object, but don't save to DB
            new_comment = comment_form.save(commit = False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the DB
            new_comment.save()
            # return http.HttpResponseRedirect('')
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form})

def post_share(request, post_id):
    # Retrive post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form field passed validation
            cd = form.cleaned_data
            # The above line, creates a dictionary of cleaned data for the form
            # If the form is not validated, then the cleaned_data, will contain only the valid fields
            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@blog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})
        

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/blog.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <div id="side-bar">
            <h2>My blog</h2>
            <p>This is my blog</p>
        </div>
    </body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}
    {{post.title}}
{% endblock %}
{% block content %}
    <h1>{{post.title}}</h1>
    <p class="date">
        Published {{post.publish}} by {{post.author}}
    </p>
    {{ post.body|linebreaks }}
    <a href="{% url 'blog:post_share' post.id %}">
        <!-- Here, we are building the URL dynamically, by using the "url" tag as provided by the Django -->
        Share this post
    </a>
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments| pluralize }}
        </h2>
    {% endwith %}
    <table>
        {% if comments.count > 0 %}
        <tr>
            <td>Sr No.</td>
            <td>Author</td>
            <td>Date of publish</td>
            <td>Comment</td>
        </tr>
        {% endif %}
        {% for comment in comments %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ comment.name }}</td>
            <td>{{ comment.created }}</td>
            <td>{{ comment.body|linebreaks }}</td>
        </tr>
            <!-- <div class="comment">
                <p class="info">
                    Comment {{ forloop.counter }} by {{ comment.name }}
                    {{ comment.created }}
                </p>
                {{ comment.body|linebreaks }}
            </div> -->
        {% empty %}
            <p>There are no comments yet.</p>
        {% endfor %}
    </table>
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% endif %}
    
    <h2>Add a new comment</h2>
    <form action="." method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
    </form>
    
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    <table>
        <tr>
            <td>
                Title
            </td>
            <td>
                Publisher
            </td>
            <td>
                Date of publish
            </td>
            <td>
                Post
            </td>
        </tr>
        {% for post in posts %}
                <tr>
                    <td>
                        <a href="{{ post.get_absolute_url }}">
                            {{post.title}}
                        </a>
                    </td>
                    <td>
                        {{ post.author }}
                    </td>
                    <td>
                        <p class="date">
                            {{ post.publish }}
                        </p>
                    </td>
                    <td>
                        {{ post.body|linebreaks|truncatewords:30 }}
                    </td>
                </tr>
        {% endfor %}
    </table>
    {% include "pagination.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
        <a href="{% url 'blog:post_list' %}">Home page</a>
    {% else %}
        <h1>
            Share "{{ post.title }}" by e-mail
        </h1>
        <form action="." method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>